<?php
function next_prev_get_nids() {
	$sorted_nids = [];  //sorted nids according to date.
	$query = \Drupal::database()->select('node_field_data', 'n');
	$query->fields('n', ['created', 'nid']);
	$query->condition('n.status', 1, '=');
	$query->condition('n.type', 'page', 'IN');
	$query->orderBy('n.created', 'DESC');
	$result = $query->execute();
	while ($row = $result->fetchAssoc()) {
		$sorted_nids[] = $row;
	}
	return $sorted_nids;
}