# Schema for the configuration files of the CKEditor block image paste module.

# Plugin \Drupal\ckeditor_blockimagepaste\Plugin\CKEditorPlugin\BlockImagePastePlugin
ckeditor.plugin.blockimagepaste:
  type: mapping
  label: 'Block image paste enabled'
  mapping:
    block_image_paste_enabled:
      type: boolean
      label: 'Use Block image paste'
